{{- if and .Values.monitoring.enabled (not .Values.upgradeTenants.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
    release: monitoring
    {{ include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: "monitoring"
  name: minio-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - interval: 30s
      port: http
      scheme: http
      path: /minio/prometheus/metrics
  jobLabel: minio
{{- end }}
