{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.minio.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: minio-operator-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "minio.labels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.minioOperator.namespaces }}
        principals: {{ .Values.istio.hardened.minioOperator.principals }}
{{- end }}
