apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator
      containers:
        - name: minio-operator
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: CLUSTER_DOMAIN
              value: {{ .Values.clusterDomain }}
            - name: WATCHED_NAMESPACE
              value: {{ .Values.watchedNamespace }}
