{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - istio-system/main
  hosts:
    - {{ include "minio.name" . }}.{{ .Values.hostname }}
  http:
    - route:
        - destination:
            host: {{ include "minio.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}

