#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name:  .Values.serviceAccountName }}
#  namespace:  .Release.Namespace }}
#imagePullSecrets:
#   toYaml .Values.imagePullSecrets | indent 2 }}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 2 }}
{{- end }}
