apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - {{ toYaml .Values.tenants.imagePullSecret | indent 2 }}
