apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ include "minio-operator.fullname" . }}
  {{- with .Values.tenant }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
    {{- if $.Values.tenant.podLabels }}
    {{- tpl (toYaml $.Values.tenant.podLabels ) $ | nindent 4 }}
    {{- end }}
  {{ if or (dig "metrics" "enabled" false .) $.Values.annotations }}
  ## Annotations for MinIO Tenant Pods
  annotations:
  {{- if $.Values.annotations }}
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
  {{- if dig "metrics" "enabled" false . }}
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: {{ dig "metrics" "port" 9000 . | quote }}
    prometheus.io/scrape: "true"
    prometheus.io/scheme: {{ dig "metrics" "protocol" "http" . | quote }}
  {{- end }}
  {{- end }}
{{- if dig "scheduler" "name" "" . }}
scheduler:
  name: {{ dig "scheduler" "name" "" . }}
{{- end }}
spec:
  image: "{{ .image.repository }}:{{ .image.digest | default .image.tag }}"
  imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" . }}
  {{- if dig "imagePullSecret" "name" "" . }}
  imagePullSecret:
    name: {{ dig "imagePullSecret" "name" "" . }}
  {{- end }}
  ## Secret with default environment variable configurations
  configuration:
    name: {{ dig "tenant" "configSecret" "name" "" ($.Values | merge (dict)) }}
  pools:
    {{- range (dig "pools" (list) .) }}
    - servers: {{ dig "servers" 4 . }}
      name: {{ dig "name" "" . }}
      volumesPerServer: {{ dig "volumesPerServer" 4 . }}
      {{- if dig "runtimeClassName" "" . }}
      runtimeClassName: {{ dig "runtimeClassName" "" . }}
      {{- end }}
      volumeClaimTemplate:
        metadata:
          name: data
      {{- with (dig "storageAnnotations" (dict) .) }}
          annotations: {{- toYaml . | nindent 12 }}
      {{- end }}
        spec:
          {{- if dig "storageClassName" "" . }}
          storageClassName: {{ dig "storageClassName" "" . }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ dig "size" "10Gi" . }}
      {{- with (dig "annotations" (dict) .) }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "labels" (dict) .) }}
      labels: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "tolerations" (list) .) }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "nodeSelector" (dict) .) }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "affinity" (dict) .) }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "resources" (dict) .) }}
      resources: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if hasKey . "securityContext" }}
      securityContext: {{- if eq (len .securityContext) 0 }} {} {{- end }}
      {{- with (dig "securityContext" (dict) .) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if hasKey . "containerSecurityContext" }}
      containerSecurityContext: {{- if eq (len .containerSecurityContext) 0 }} {} {{- end }}
      {{- with (dig "containerSecurityContext" (dict) .) }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with (dig "topologySpreadConstraints" (list) .) }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  mountPath: {{ dig "mountPath" "/export" . }}
  subPath: {{ dig "subPath" "/data" . }}
  {{- with (dig "certificate" "externalCaCertSecret" (list) .) }}
  externalCaCertSecret: {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with (dig "certificate" "externalCertSecret" (list) .) }}
  externalCertSecret: {{- toYaml . | nindent 6 }}
  {{- end }}
  requestAutoCert: {{ dig "certificate" "requestAutoCert" false . }}
  {{- if ((.certificate).certExpiryAlertThreshold) }}
  certExpiryAlertThreshold: {{ ((.certificate).certExpiryAlertThreshold) }}
  {{- end }}
  {{- if dig "s3" "bucketDNS" false . }}
    {{- fail "Value 'tenant.s3.bucketDNS' is deprecated since Operator v4.3.2, use 'tenant.features.bucketDNS' instead" }}
  {{- end }}
  features:
    bucketDNS: {{ dig "features" "bucketDNS" false . }}
    {{- with (dig "features" "domains" (dict) .) }}
    domains: {{- toYaml . | nindent 6 }}
    {{- end }}
    enableSFTP: {{ dig "features" "enableSFTP" false . }}
  {{- with (dig "buckets" (list) .) }}
  buckets: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "users" (list) .) }}
  users: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "certificate" "certConfig" (dict) .) }}
  certConfig: {{- toYaml . | nindent 4 }}
  {{- end }}
  podManagementPolicy: {{ dig "podManagementPolicy" "Parallel" . }}
  {{- with (dig "readiness" (dict) .) }}
  readiness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "liveness" (dict) .) }}
  liveness: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "startup" (dict) .) }}
  startup: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "lifecycle" (dict) .) }}
  lifecycle: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "exposeServices" (dict) .) }}
  exposeServices: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "serviceAccountName" "" . }}
  serviceAccountName: {{ dig "serviceAccountName" "" . }}
  {{- end }}
  prometheusOperator: {{ dig "prometheusOperator" "false" . }}
  {{- with (dig "logging" (dict) .) }}
  logging: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "serviceMetadata" (dict) .) }}
  serviceMetadata: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "env" (list) .) }}
  env: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "priorityClassName" "" . }}
  priorityClassName: {{ dig "priorityClassName" "" . }}
  {{- end }}
  {{- with (dig "additionalVolumes" (list) .) }}
  additionalVolumes: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "additionalVolumeMounts" (list) .) }}
  additionalVolumeMounts: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if dig "kes" "configuration" false . }}
  kes:
    image: "{{ .kes.image.repository }}:{{ .kes.image.digest | default .kes.image.tag }}"
    {{- with (dig "kes" "env" (list) .) }}
    env: {{- toYaml . | nindent 4 }}
    {{- end }}
    replicas: {{ .kes.replicas | int }}
    kesSecret:
      name: "kes-configuration"
    imagePullPolicy: {{ .kes.imagePullPolicy | quote }}
    {{- with (dig "kes" "externalCertSecret" (dict) .) }}
    externalCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "kes" "clientCertSecret" (dict) .) }}
    clientCertSecret: {{- toYaml . | nindent 6 }}
    {{- end }}
    ## Key name to be created on the KMS, default is "my-minio-key"
    keyName: {{ .kes.keyName | quote }}
    {{- with (dig "resources" (dict) .) }}
    resources: {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "nodeSelector" (dict) .) }}
    nodeSelector: {{- toYaml . | nindent 4 }}
    {{- end }}
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    tolerations: []
    {{- with (dig "annotations" (dict) .) }}
    annotations: {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "labels" (dict) .) }}
    labels: {{- toYaml . | nindent 4 }}
    {{- end }}
    serviceAccountName: {{ .kes.serviceAccountName | quote }}
    {{- if hasKey .kes "securityContext" }}
    securityContext: {{- if eq (len .kes.securityContext) 0 }} {} {{- end }}
    {{- with (dig "kes" "securityContext" (dict) .) }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if hasKey .kes "containerSecurityContext" }}
    containerSecurityContext: {{- if eq (len .kes.containerSecurityContext) 0 }} { } {{- end }}
      {{- with (dig "kes" "containerSecurityContext" (dict) .) }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
  {{- end }}

  {{- if ne (dig "prometheus" "disabled" false .) true}}
  ## Prometheus setup for MinIO Tenant.
  prometheus:
    image: {{ .prometheus.image | quote }}
    {{- with (dig "prometheus" "env" (list) .) }}
    env:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    sidecarimage: {{ .prometheus.sidecarimage | quote }}
    initimage: {{ .prometheus.initimage | quote }}
    diskCapacityGB: {{ .prometheus.diskCapacityGB | int }}
    storageClassName: {{ .prometheus.storageClassName }}
    {{- with (dig "prometheus" "annotations" (dict) .) }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "prometheus" "labels" (dict) .) }}
    labels:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "prometheus" "nodeSelector" (dict) .) }}
    nodeSelector:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "prometheus" "affinity" (dict) .) }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "prometheus" "tolerations" (list) .) }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "prometheus" "resources" (dict) .) }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    serviceAccountName: {{ .prometheus.serviceAccountName | quote }}
    securityContext:
      runAsUser: {{ .prometheus.securityContext.runAsUser | int }}
      runAsGroup: {{ .prometheus.securityContext.runAsGroup | int }}
      runAsNonRoot: {{ .prometheus.securityContext.runAsNonRoot }}
      fsGroup: {{ .prometheus.securityContext.fsGroup | int }}
  {{- end }}

  {{- if ne (dig "log" "disabled" false .) true}}
  ## LogSearch API setup for MinIO Tenant.
  log:
    image: {{ .log.image | quote }}
    {{- with (dig "log" "env" (list) .) }}
    env:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "log" "resources" (dict) .) }}
    resources:
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "log" "nodeSelector" (dict) .) }}
    nodeSelector:
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "log" "affinity" (dict) .) }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "log" "tolerations" (list) .) }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with (dig "log" "annotations" (dict) .) }}
    annotations:
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "log" "labels" (dict) .) }}
    labels:
      {{ toYaml . | nindent 4 }}
    {{- end }}
    audit:
      diskCapacityGB: {{ .log.audit.diskCapacityGB | int }}
    db:
      image: {{ .log.db.image | quote }}
      {{- with (dig "log" "db" "env" (list) .) }}
      env:
      {{- range . }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
      {{- end }}
      {{- end }}
      initimage: {{ .log.db.initimage | quote }}
      volumeClaimTemplate:
        {{- with (dig "log" "db" "volumeClaimTemplate" "metadata" (dict) .) }}
        metadata:
          {{ toYaml . | nindent 4 }}
        {{- end }}
        spec:
          storageClassName: {{ .log.db.volumeClaimTemplate.spec.storageClassName | quote }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .log.db.volumeClaimTemplate.spec.resources.requests.storage | quote }}
      {{- with (dig "log" "db" "resources" (dict) .) }}
      resources:
        {{ toYaml . | nindent 4 }}
      {{- end }}
      {{- with (dig "log" "db" "nodeSelector" (dict) .) }}
      nodeSelector:
        {{ toYaml . | nindent 4 }}
      {{- end }}
      {{- with (dig "log" "db" "affinity" (dict) .) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "log" "db" "tolerations" (list) .) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (dig "log" "db" "annotations" (dict) .) }}
      annotations:
        {{ toYaml . | nindent 4 }}
      {{- end }}
      {{- with (dig "log" "db" "labels" (dict) .) }}
      labels:
        {{ toYaml . | nindent 4 }}
      {{- end }}
      serviceAccountName: {{ .log.db.serviceAccountName | quote }}
      securityContext:
        runAsUser: {{ .log.db.securityContext.runAsUser | int }}
        runAsGroup: {{ .log.db.securityContext.runAsGroup | int }}
        runAsNonRoot: true
        fsGroup: {{ .log.db.securityContext.fsGroup | int }}
    serviceAccountName: {{ .log.serviceAccountName | quote }}
    securityContext:
      runAsUser: {{ .log.securityContext.runAsUser | int }}
      runAsGroup: {{ .log.securityContext.runAsGroup | int }}
      runAsNonRoot: true
      fsGroup: {{ .log.securityContext.fsGroup | int }}
  {{- end }}
  {{ if dig "priorityClassName" "" . }}
  priorityClassName: {{ dig "priorityClassName" "" . }}
  {{- end }}
{{- end }}
