{{- if not .Values.upstream.tenant.configSecret.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: minio-access
stringData:
  ## Access Key for MinIO Tenant
  accesskey: {{ dig "upstream" "tenant" "configSecret" "accessKey" "" (.Values | merge (dict)) }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ dig "upstream" "tenant" "configSecret" "secretKey" "" (.Values | merge (dict)) }}

{{- end }}