{{- if and .Values.istio.enabled .Values.istio.console.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "minio-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minio-operator.fullname" . }}
    {{- include "minio-operator.labels" . | nindent 4 }}
  {{- if .Values.istio.console.labels }}
    {{ toYaml .Values.istio.console.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.console.annotations }}
  annotations:
    {{ toYaml .Values.istio.console.annotations | indent 2 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.console.gateways }}
  - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.console.hosts }}
  - {{ tpl . $}}
  {{- end }}
  http:
    - match:
        - uri:
            prefix: /minio/v2/metrics/cluster
      route:
        - destination:
            host: {{ include "minio-operator.fullname" . | trim }}-console
            port:
              number: {{ include "minio-operator.servicePort" . | trim }}
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 403
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            # Note: the minio operator creates the service for the tenant with a fixed name
            host: {{ include "minio-operator.fullname" . | trim }}-console
            port:
              number: {{ include "minio-operator.servicePort" . | trim }}
  {{ end }}
