apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator

# Configure number of MinIO Operator Deployment Replicas
replicas:
  - name: minio-operator
    count: 1

# use IronBank hardened image
images:
  - name: minio/k8s-operator
    newName: registry.dsop.io/platform-one/apps/minio/operator
    newTag: 2.0.9

# Configure the Cluster Domain and NameSpace to Watch
configMapGenerator:
  - name: operator-env
    literals:
    - CLUSTER_DOMAIN="cluster.local"
    - WATCHED_NAMESPACE="minio"

# Configure the Namespace and ServiceAccount name
patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: minio-operator
    patch: |-
      - op: replace
        path: /metadata/name
        value: "minio-operator"
  - target:
      version: v1
      kind: Namespace
      name: minio-operator
    patch: |-
      - op: replace
        path: /metadata/name
        value: "minio-operator"

vars:
  - name: CLUSTER_DOMAIN
    objref:
      kind: ConfigMap
      name: operator-env
      apiVersion: v1
    fieldref:
      fieldpath: data.CLUSTER_DOMAIN
  - name: WATCHED_NAMESPACE
    objref:
      kind: ConfigMap
      name: operator-env
      apiVersion: v1
    fieldref:
      fieldpath: data.WATCHED_NAMESPACE

resources:
  - upstream/namespace.yaml
  - upstream/service-account.yaml
  - upstream/crd.yaml
  - upstream/rbac.yaml
  - upstream/deployment.yaml
